// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkR56eU2nsl4v9YWol1m_ovYpYOpzJnE',
    appId: '1:694653529668:web:6edd18884efd3842d51611',
    messagingSenderId: '694653529668',
    projectId: 'taskwise-470d7',
    authDomain: 'taskwise-470d7.firebaseapp.com',
    storageBucket: 'taskwise-470d7.appspot.com',
    measurementId: 'G-FN6D4ZRH91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdUOVlC-dIvPScvTobvNHGAbqFr5emBU',
    appId: '1:694653529668:android:80453e3cda3d5c81d51611',
    messagingSenderId: '694653529668',
    projectId: 'taskwise-470d7',
    storageBucket: 'taskwise-470d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbbFA2eOosY0gXscKfTBrPXCp92wNF39M',
    appId: '1:694653529668:ios:57698d81116167a8d51611',
    messagingSenderId: '694653529668',
    projectId: 'taskwise-470d7',
    storageBucket: 'taskwise-470d7.appspot.com',
    iosBundleId: 'com.example.taskwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbbFA2eOosY0gXscKfTBrPXCp92wNF39M',
    appId: '1:694653529668:ios:57698d81116167a8d51611',
    messagingSenderId: '694653529668',
    projectId: 'taskwise-470d7',
    storageBucket: 'taskwise-470d7.appspot.com',
    iosBundleId: 'com.example.taskwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSkR56eU2nsl4v9YWol1m_ovYpYOpzJnE',
    appId: '1:694653529668:web:08fdc3d285d586aed51611',
    messagingSenderId: '694653529668',
    projectId: 'taskwise-470d7',
    authDomain: 'taskwise-470d7.firebaseapp.com',
    storageBucket: 'taskwise-470d7.appspot.com',
    measurementId: 'G-K43MPLKMK1',
  );
}
